version: "3.9"

services:
  mariadb_server:
    container_name: mariadb
    image: mariadb:latest
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=password
    networks:
      - maria-network
    volumes:
      - db:/var/lib/docker-volumes/mariadb-volumes/

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin:latest
    restart: always
    depends_on:
      - mariadb_server
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mariadb
      - PMA_USER=root
      - PMA_PASSWORD=password
      - UPLOAD_LIMIT=1G
    networks:
      - maria-network
    ports:
      - "4500:80"

networks:
  maria-network:
    driver: bridge

volumes:
  db: